// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Scio.Data;
using Scio.Data.Models;

namespace Scio.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class ForumVotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ForumVotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Administration/ForumVotes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ForumVotes.Include(f => f.Post).Include(f => f.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/ForumVotes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumVote = await _context.ForumVotes
                .Include(f => f.Post)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forumVote == null)
            {
                return NotFound();
            }

            return View(forumVote);
        }

        // GET: Administration/ForumVotes/Create
        public IActionResult Create()
        {
            ViewData["PostId"] = new SelectList(_context.ForumPosts, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Administration/ForumVotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Type,PostId,UserId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] ForumVote forumVote)
        {
            if (ModelState.IsValid)
            {
                _context.Add(forumVote);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostId"] = new SelectList(_context.ForumPosts, "Id", "Id", forumVote.PostId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", forumVote.UserId);
            return View(forumVote);
        }

        // GET: Administration/ForumVotes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumVote = await _context.ForumVotes.FindAsync(id);
            if (forumVote == null)
            {
                return NotFound();
            }
            ViewData["PostId"] = new SelectList(_context.ForumPosts, "Id", "Id", forumVote.PostId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", forumVote.UserId);
            return View(forumVote);
        }

        // POST: Administration/ForumVotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Type,PostId,UserId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] ForumVote forumVote)
        {
            if (id != forumVote.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forumVote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumVoteExists(forumVote.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostId"] = new SelectList(_context.ForumPosts, "Id", "Id", forumVote.PostId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", forumVote.UserId);
            return View(forumVote);
        }

        // GET: Administration/ForumVotes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumVote = await _context.ForumVotes
                .Include(f => f.Post)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forumVote == null)
            {
                return NotFound();
            }

            return View(forumVote);
        }

        // POST: Administration/ForumVotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var forumVote = await _context.ForumVotes.FindAsync(id);
            _context.ForumVotes.Remove(forumVote);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ForumVoteExists(string id)
        {
            return _context.ForumVotes.Any(e => e.Id == id);
        }
    }
}
