// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Scio.Data;
using Scio.Data.Models;

namespace Scio.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class ForumPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ForumPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Administration/ForumPosts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ForumPosts.Include(f => f.Author).Include(f => f.Question);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/ForumPosts/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumPost = await _context.ForumPosts
                .Include(f => f.Author)
                .Include(f => f.Question)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forumPost == null)
            {
                return NotFound();
            }

            return View(forumPost);
        }

        // GET: Administration/ForumPosts/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["QuestionId"] = new SelectList(_context.ForumPosts, "Id", "Id");
            return View();
        }

        // POST: Administration/ForumPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Body,AuthorId,QuestionId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] ForumPost forumPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(forumPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", forumPost.AuthorId);
            ViewData["QuestionId"] = new SelectList(_context.ForumPosts, "Id", "Id", forumPost.QuestionId);
            return View(forumPost);
        }

        // GET: Administration/ForumPosts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumPost = await _context.ForumPosts.FindAsync(id);
            if (forumPost == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", forumPost.AuthorId);
            ViewData["QuestionId"] = new SelectList(_context.ForumPosts, "Id", "Id", forumPost.QuestionId);
            return View(forumPost);
        }

        // POST: Administration/ForumPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Title,Body,AuthorId,QuestionId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] ForumPost forumPost)
        {
            if (id != forumPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forumPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumPostExists(forumPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", forumPost.AuthorId);
            ViewData["QuestionId"] = new SelectList(_context.ForumPosts, "Id", "Id", forumPost.QuestionId);
            return View(forumPost);
        }

        // GET: Administration/ForumPosts/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumPost = await _context.ForumPosts
                .Include(f => f.Author)
                .Include(f => f.Question)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forumPost == null)
            {
                return NotFound();
            }

            return View(forumPost);
        }

        // POST: Administration/ForumPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var forumPost = await _context.ForumPosts.FindAsync(id);
            _context.ForumPosts.Remove(forumPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ForumPostExists(string id)
        {
            return _context.ForumPosts.Any(e => e.Id == id);
        }
    }
}
